package models;

import javax.persistence.Entity;
import javax.persistence.Id;

// Generated 28 Mar, 2017 12:23:43 AM by Hibernate Tools 5.2.1.Final

/**
 * Bscit generated by hbm2java
 */
@Entity
public class Bscit implements java.io.Serializable {
	@Id
	private Integer rollno;
	private String studname;
	private String dob;
	private String fname;
	private String mname;
	private String phone;
	private String sem;
	private String address;
	private String gender;
	private Integer s1i;
	private Integer s1p;
	private Integer s1t;
	private Integer s2i;
	private Integer s2p;
	private Integer s2t;
	private Integer s3i;
	private Integer s3p;
	private Integer s3t;
	private Integer s4i;
	private Integer s4p;
	private Integer s4t;
	private Integer s5i;
	private Integer s5p;
	private Integer s5t;
	private Integer s1ittotal;
	private Integer s2ittotal;
	private Integer s3ittotal;
	private Integer s4ittotal;
	private Integer s5ittotal;
	private Integer s1itptotal;
	private Integer s2itptotal;
	private Integer s3itptotal;
	private Integer s4itptotal;
	private Integer s5itptotal;
	private Integer grandtotal;
	private Float percentage;
	private String s1git;
	private String s2git;
	private String s3git;
	private String s4git;
	private String s5git;
	private String s1gp;
	private String s2gp;
	private String s3gp;
	private String s4gp;
	private String s5gp;
	private Integer s1gpit;
	private Integer s2gpit;
	private Integer s3gpit;
	private Integer s4gpit;
	private Integer s5gpit;
	private Integer s1gpp;
	private Integer s2gpp;
	private Integer s3gpp;
	private Integer s4gpp;
	private Integer s5gpp;
	private Integer s1cpit;
	private Integer s2cpit;
	private Integer s3cpit;
	private Integer s4cpit;
	private Integer s5cpit;
	private Integer s1cpp;
	private Integer s2cpp;
	private Integer s3cpp;
	private Integer s4cpp;
	private Integer s5cpp;
	private Integer cptotal;
	private Integer s1cxgit;
	private Integer s2cxgit;
	private Integer s3cxgit;
	private Integer s4cxgit;
	private Integer s5cxgit;
	private Integer s1cxgp;
	private Integer s2cxgp;
	private Integer s3cxgp;
	private Integer s4cxgp;
	private Integer s5cxgp;
	private Integer cxgtotal;
	private Float cgpa;
	private String finalgrade;
	private byte[] photo;

	public Bscit() {
	}

	public Bscit(String sem) {
		this.sem = sem;
	}

	public Integer getRollno() {
		return this.rollno;
	}

	public void setRollno(Integer rollno) {
		this.rollno = rollno;
	}

	public String getStudname() {
		return this.studname;
	}

	public void setStudname(String studname) {
		this.studname = studname;
	}

	public String getDob() {
		return dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}
	
	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getMname() {
		return mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}
	
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	public String getSem() {
		return this.sem;
	}

	public void setSem(String sem) {
		this.sem = sem;
	}
	
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
	
	public Integer getS1i() {
		return this.s1i;
	}

	public void setS1i(Integer s1i) {
		this.s1i = s1i;
	}

	public Integer getS1p() {
		return this.s1p;
	}

	public void setS1p(Integer s1p) {
		this.s1p = s1p;
	}

	public Integer getS1t() {
		return this.s1t;
	}

	public void setS1t(Integer s1t) {
		this.s1t = s1t;
	}

	public Integer getS2i() {
		return this.s2i;
	}

	public void setS2i(Integer s2i) {
		this.s2i = s2i;
	}

	public Integer getS2p() {
		return this.s2p;
	}

	public void setS2p(Integer s2p) {
		this.s2p = s2p;
	}

	public Integer getS2t() {
		return this.s2t;
	}

	public void setS2t(Integer s2t) {
		this.s2t = s2t;
	}

	public Integer getS3i() {
		return this.s3i;
	}

	public void setS3i(Integer s3i) {
		this.s3i = s3i;
	}

	public Integer getS3p() {
		return this.s3p;
	}

	public void setS3p(Integer s3p) {
		this.s3p = s3p;
	}

	public Integer getS3t() {
		return this.s3t;
	}

	public void setS3t(Integer s3t) {
		this.s3t = s3t;
	}

	public Integer getS4i() {
		return this.s4i;
	}

	public void setS4i(Integer s4i) {
		this.s4i = s4i;
	}

	public Integer getS4p() {
		return this.s4p;
	}

	public void setS4p(Integer s4p) {
		this.s4p = s4p;
	}

	public Integer getS4t() {
		return this.s4t;
	}

	public void setS4t(Integer s4t) {
		this.s4t = s4t;
	}

	public Integer getS5i() {
		return this.s5i;
	}

	public void setS5i(Integer s5i) {
		this.s5i = s5i;
	}

	public Integer getS5p() {
		return this.s5p;
	}

	public void setS5p(Integer s5p) {
		this.s5p = s5p;
	}

	public Integer getS5t() {
		return this.s5t;
	}

	public void setS5t(Integer s5t) {
		this.s5t = s5t;
	}

	public Integer getS1ittotal() {
		return this.s1ittotal;
	}

	public void setS1ittotal(Integer s1ittotal) {
		this.s1ittotal = s1ittotal;
	}

	public Integer getS2ittotal() {
		return this.s2ittotal;
	}

	public void setS2ittotal(Integer s2ittotal) {
		this.s2ittotal = s2ittotal;
	}

	public Integer getS3ittotal() {
		return this.s3ittotal;
	}

	public void setS3ittotal(Integer s3ittotal) {
		this.s3ittotal = s3ittotal;
	}

	public Integer getS4ittotal() {
		return this.s4ittotal;
	}

	public void setS4ittotal(Integer s4ittotal) {
		this.s4ittotal = s4ittotal;
	}

	public Integer getS5ittotal() {
		return this.s5ittotal;
	}

	public void setS5ittotal(Integer s5ittotal) {
		this.s5ittotal = s5ittotal;
	}

	public Integer getGrandtotal() {
		return this.grandtotal;
	}

	public Integer getS1itptotal() {
		return s1itptotal;
	}

	public void setS1itptotal(Integer s1itptotal) {
		this.s1itptotal = s1itptotal;
	}

	public Integer getS2itptotal() {
		return s2itptotal;
	}

	public void setS2itptotal(Integer s2itptotal) {
		this.s2itptotal = s2itptotal;
	}

	public Integer getS3itptotal() {
		return s3itptotal;
	}

	public void setS3itptotal(Integer s3itptotal) {
		this.s3itptotal = s3itptotal;
	}

	public Integer getS4itptotal() {
		return s4itptotal;
	}

	public void setS4itptotal(Integer s4itptotal) {
		this.s4itptotal = s4itptotal;
	}

	public Integer getS5itptotal() {
		return s5itptotal;
	}

	public void setS5itptotal(Integer s5itptotal) {
		this.s5itptotal = s5itptotal;
	}
	
	public void setGrandtotal(Integer grandtotal) {
		this.grandtotal = grandtotal;
	}

	public Float getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Float percentage) {
		this.percentage = percentage;
	}
	
	public String getS1git() {
		return s1git;
	}

	public void setS1git(String s1git) {
		this.s1git = s1git;
	}

	public String getS2git() {
		return s2git;
	}

	public void setS2git(String s2git) {
		this.s2git = s2git;
	}

	public String getS3git() {
		return s3git;
	}

	public void setS3git(String s3git) {
		this.s3git = s3git;
	}

	public String getS4git() {
		return s4git;
	}

	public void setS4git(String s4git) {
		this.s4git = s4git;
	}

	public String getS5git() {
		return s5git;
	}

	public void setS5git(String s5git) {
		this.s5git = s5git;
	}

	public String getS1gp() {
		return s1gp;
	}

	public void setS1gp(String s1gp) {
		this.s1gp = s1gp;
	}

	public String getS2gp() {
		return s2gp;
	}

	public void setS2gp(String s2gp) {
		this.s2gp = s2gp;
	}

	public String getS3gp() {
		return s3gp;
	}

	public void setS3gp(String s3gp) {
		this.s3gp = s3gp;
	}

	public String getS4gp() {
		return s4gp;
	}

	public void setS4gp(String s4gp) {
		this.s4gp = s4gp;
	}

	public String getS5gp() {
		return s5gp;
	}

	public void setS5gp(String s5gp) {
		this.s5gp = s5gp;
	}

	public Integer getS1gpit() {
		return s1gpit;
	}

	public void setS1gpit(Integer s1gpit) {
		this.s1gpit = s1gpit;
	}

	public Integer getS2gpit() {
		return s2gpit;
	}

	public void setS2gpit(Integer s2gpit) {
		this.s2gpit = s2gpit;
	}

	public Integer getS3gpit() {
		return s3gpit;
	}

	public void setS3gpit(Integer s3gpit) {
		this.s3gpit = s3gpit;
	}

	public Integer getS4gpit() {
		return s4gpit;
	}

	public void setS4gpit(Integer s4gpit) {
		this.s4gpit = s4gpit;
	}

	public Integer getS5gpit() {
		return s5gpit;
	}

	public void setS5gpit(Integer s5gpit) {
		this.s5gpit = s5gpit;
	}

	public Integer getS1gpp() {
		return s1gpp;
	}

	public void setS1gpp(Integer s1gpp) {
		this.s1gpp = s1gpp;
	}

	public Integer getS2gpp() {
		return s2gpp;
	}

	public void setS2gpp(Integer s2gpp) {
		this.s2gpp = s2gpp;
	}

	public Integer getS3gpp() {
		return s3gpp;
	}

	public void setS3gpp(Integer s3gpp) {
		this.s3gpp = s3gpp;
	}

	public Integer getS4gpp() {
		return s4gpp;
	}

	public void setS4gpp(Integer s4gpp) {
		this.s4gpp = s4gpp;
	}

	public Integer getS5gpp() {
		return s5gpp;
	}

	public void setS5gpp(Integer s5gpp) {
		this.s5gpp = s5gpp;
	}

	public Integer getS1cpit() {
		return s1cpit;
	}

	public void setS1cpit(Integer s1cpit) {
		this.s1cpit = s1cpit;
	}

	public Integer getS2cpit() {
		return s2cpit;
	}

	public void setS2cpit(Integer s2cpit) {
		this.s2cpit = s2cpit;
	}

	public Integer getS3cpit() {
		return s3cpit;
	}

	public void setS3cpit(Integer s3cpit) {
		this.s3cpit = s3cpit;
	}

	public Integer getS4cpit() {
		return s4cpit;
	}

	public void setS4cpit(Integer s4cpit) {
		this.s4cpit = s4cpit;
	}

	public Integer getS5cpit() {
		return s5cpit;
	}

	public void setS5cpit(Integer s5cpit) {
		this.s5cpit = s5cpit;
	}

	public Integer getS1cpp() {
		return s1cpp;
	}

	public void setS1cpp(Integer s1cpp) {
		this.s1cpp = s1cpp;
	}

	public Integer getS2cpp() {
		return s2cpp;
	}

	public void setS2cpp(Integer s2cpp) {
		this.s2cpp = s2cpp;
	}

	public Integer getS3cpp() {
		return s3cpp;
	}

	public void setS3cpp(Integer s3cpp) {
		this.s3cpp = s3cpp;
	}

	public Integer getS4cpp() {
		return s4cpp;
	}

	public void setS4cpp(Integer s4cpp) {
		this.s4cpp = s4cpp;
	}

	public Integer getS5cpp() {
		return s5cpp;
	}

	public void setS5cpp(Integer s5cpp) {
		this.s5cpp = s5cpp;
	}

	public Integer getCptotal() {
		return this.cptotal;
	}

	public void setCptotal(Integer cptotal) {
		this.cptotal = cptotal;
	}

	
	public Integer getS1cxgit() {
		return s1cxgit;
	}

	public void setS1cxgit(Integer s1cxgit) {
		this.s1cxgit = s1cxgit;
	}

	public Integer getS2cxgit() {
		return s2cxgit;
	}

	public void setS2cxgit(Integer s2cxgit) {
		this.s2cxgit = s2cxgit;
	}

	public Integer getS3cxgit() {
		return s3cxgit;
	}

	public void setS3cxgit(Integer s3cxgit) {
		this.s3cxgit = s3cxgit;
	}

	public Integer getS4cxgit() {
		return s4cxgit;
	}

	public void setS4cxgit(Integer s4cxgit) {
		this.s4cxgit = s4cxgit;
	}

	public Integer getS5cxgit() {
		return s5cxgit;
	}

	public void setS5cxgit(Integer s5cxgit) {
		this.s5cxgit = s5cxgit;
	}

	public Integer getS1cxgp() {
		return s1cxgp;
	}

	public void setS1cxgp(Integer s1cxgp) {
		this.s1cxgp = s1cxgp;
	}

	public Integer getS2cxgp() {
		return s2cxgp;
	}

	public void setS2cxgp(Integer s2cxgp) {
		this.s2cxgp = s2cxgp;
	}

	public Integer getS3cxgp() {
		return s3cxgp;
	}

	public void setS3cxgp(Integer s3cxgp) {
		this.s3cxgp = s3cxgp;
	}

	public Integer getS4cxgp() {
		return s4cxgp;
	}

	public void setS4cxgp(Integer s4cxgp) {
		this.s4cxgp = s4cxgp;
	}

	public Integer getS5cxgp() {
		return s5cxgp;
	}

	public void setS5cxgp(Integer s5cxgp) {
		this.s5cxgp = s5cxgp;
	}

	public Integer getCxgtotal() {
		return this.cxgtotal;
	}

	public void setCxgtotal(Integer cxgtotal) {
		this.cxgtotal = cxgtotal;
	}

	public Float getCgpa() {
		return this.cgpa;
	}

	public void setCgpa(Float cgpa) {
		this.cgpa = cgpa;
	}

	public String getFinalgrade() {
		return this.finalgrade;
	}

	public void setFinalgrade(String finalgrade) {
		this.finalgrade = finalgrade;
	}

	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

}
